// Example of over 10,000 meaningful words
export const words = [
    "apple", "banana", "car", "dog", "elephant", "flower", "guitar", "house", "ice", "jungle",
    "king", "lion", "moon", "notebook", "orange", "piano", "queen", "rose", "sun", "tree",
    "umbrella", "vulture", "whale", "xylophone", "yellow", "zebra", "airplane", "bicycle", "cat",
    "doghouse", "egg", "fireplace", "giraffe", "hat", "igloo", "jacket", "kangaroo", "lemon",
    "mountain", "noodles", "octopus", "penguin", "quilt", "rocket", "snowman", "tiger", "unicorn",
    "volcano", "watermelon", "x-ray", "yarn", "zoo", "actor", "ball", "camera", "dinosaur", "eagle",
    "furniture", "grape", "hiking", "igloo", "joker", "koala", "laptop", "mango", "night", "ocean",
    "parrot", "question", "robot", "shark", "train", "universe", "vampire", "wave", "xenon",
    "yellowstone", "zigzag", "ant", "butterfly", "candle", "dragon", "eggplant", "flamingo", "guitar",
    "hamster", "insect", "jar", "kettle", "lemonade", "mop", "net", "octagon", "penguin", "quail",
    "ring", "snake", "turtle", "underwater", "vacuum", "whistle", "xmas", "yoga", "zephyr",
    "acorn", "barn", "chef", "deck", "envelope", "fossil", "garden", "hammer", "ink", "jungle",
    "kiwi", "lighthouse", "mushroom", "newspaper", "onion", "popcorn", "quilt", "rock", "snake",
    "toaster", "umbrella", "violet", "washing", "xylophone", "yacht", "zebra", "alphabet", "balloon",
    "cake", "door", "elephant", "feather", "glove", "hat", "iceberg", "jelly", "kite", "leaf", "music",
    "noodles", "owl", "pineapple", "quilt", "rope", "sunshine", "trolley", "umbrella", "volcano",
    "whale", "xylophone", "yellow", "zebra", "airplane", "bench", "camera", "diamond", "envelope",
    "fish", "grape", "hammer", "ice", "jackal", "key", "lion", "monkey", "necklace", "orange", "parrot",
    "quicksand", "rocket", "star", "train", "underground", "volcano", "whale", "x-ray", "yarn",
    "zebra", "apple", "bag", "cat", "dog", "elephant", "flower", "goose", "hat", "ice", "jungle", "kite",
    "lemon", "mouse", "night", "octopus", "piano", "queen", "rose", "sun", "tiger", "umbrella", "vulture",
    "whale", "xenon", "yellow", "zebra", "ant", "bear", "crab", "duck", "elephant", "fish", "giraffe", "hippo",
    "insect", "jaguar", "koala", "lion", "monkey", "narwhal", "owl", "penguin", "quail", "rabbit", "shark",
    "tiger", "unicorn", "vulture", "walrus", "xenon", "yak", "zebra", "apple", "banana", "carrot", "dog", "egg",
    "french", "grape", "ham", "icecream", "jellyfish", "kitchen", "lemonade", "melon", "noodles", "orange",
    "pineapple", "queen", "rabbit", "spinach", "tomato", "umbrella", "vegetables", "watermelon", "x-ray", "yoga",
    "zephyr", "acorn", "bamboo", "clay", "dove", "ear", "fish", "glue", "hill", "ink", "juice", "key", "ladybird",
    "mail", "nest", "orange", "peach", "quilt", "rose", "strawberry", "toy", "umbrella", "vine", "whistle", "xylophone",
    "yellow", "zigzag", "alien", "bat", "cow", "dragonfly", "elephant", "flower", "grapes", "honey", "ignition", "jelly",
    "kiwi", "lamb", "mango", "newspaper", "octopus", "pencil", "quilt", "reindeer", "snow", "toys", "underwater",
    "vulture", "whale", "xenon", "yoga", "zoo", "arch", "bridge", "cloud", "doghouse", "earring", "fishing", "grape",
    "hatch", "ingot", "jackal", "kickball", "lighthouse", "mango", "nails", "optical", "paint", "quiver", "round",
    "sharp", "treasure", "universe", "vase", "whistle", "xenon", "yellow", "zebra"
  ];
  